config/routes.rb
Rails.application.routes.draw do

  devise_for :users
	root "lists#index"

	resources :lists

	post 'lists/:id/add' => 'lists#add_item'
	delete 'lists/:id/:item' => 'lists#delete_item'
	get 'lists/:id/send' => 'lists#send_form', as: "send_form"
	post 'lists/:id/send' => 'lists#send_list'

end

app/models/list.rb
class List < ActiveRecord::Base
	serialize :list_items
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :lists, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_list, only: [:show, :edit, :update, :destroy, :add_item, :delete_item, :send_form, :send_list]
  before_action :confirm_owner, only: [:show, :edit, :update, :destroy, :add_item, :delete_item, :send_form, :send_list]

  # GET /lists
  # GET /lists.json
  def index
	  @list = List.new(user_id: current_user)
	  @lists = List.where user_id: current_user.id
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
  end

  # GET /lists/new
  def new
    @list = List.new
  end

  # GET /lists/1/edit
  def edit
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(list_params)
	@list.user_id = current_user.id
    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render :show, status: :created, location: @list }
      else
        format.html { render :new }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lists/1
  # PATCH/PUT /lists/1.json
  def update
    respond_to do |format|
      if @list.update(list_params)
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { render :show, status: :ok, location: @list }
      else
        format.html { render :edit }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list.destroy
    respond_to do |format|
      format.html { redirect_to lists_url, notice: 'List was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # POST /lists/1/add
  def add_item
	  respond_to do |format|
		  item = params[:item]
		  @list.list_items = @list.list_items ? @list.list_items.push(item) : [item]
		  if @list.save
			  format.html { render :edit, notice: (item + ' - successfully added!') }
			  format.json { render :show, status: :ok, location: @list }
		  else
			  format.html { render :edit }
			  format.json { render json: @list.errors, status: :unprocessable_entity }
		  end
	  end
  end

  # DELETE /lists/1/bananas
  def delete_item
	  respond_to do |format|
		  item = params[:item]
		  @list.list_items.delete item
		  if @list.save
			  format.html { render :edit, notice: (item + ' - successfully removed!') }
			  format.json { render :show, status: :ok, location: @list }
		  else
			  format.html { render :edit }
			  format.json { render json: @list.errors, status: :unprocessable_entity }
		  end
	  end
  end

  def unauthorized
  end

  def send_form
  end

  def send_list
	  to_email = params['to_email']
	  message = params['message']
	  ListMailer.email_list(@list, current_user.email, to_email, message).deliver
	  redirect_to @list, notice: "Your list has been sent!"
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list
      @list = List.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def list_params
      params[:list].permit(:title)
	end

  	# confirm the current user actually has access
	def confirm_owner
		render :unauthorized if current_user.id != @list.user_id
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Listache</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= csrf_meta_tags %>
</head>
<body>
<header class="app-header">
  <div class="container">
	<div class="row">
	  <div class="col-sm-8 col-sm-push-2 text-center">
		<%= image_tag "listache.png", width: "400" %>
		<h1 class="sr-only">Listache</h1>
		<% if user_signed_in? %>
			<hr/>
			<%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "btn btn-default" %>
		<% end %>
	  </div>
	</div>
  </div>
</header>
<main class="container">
  <div class="row">
	<div class="col-sm-8 col-sm-push-2">
	  <p class="notice"><%= notice %></p>
	  <p class="alert"><%= alert %></p>
	  <%= yield %>
	</div>
  </div>
</main>
</body>
</html>

app/views/lists/_form.html.erb
<%= form_for(@list) do |f| %>
	<div class="field">
	  <%= f.label :title, class: "control-label" %>
	  <div class="input-group">
		<%= f.text_field :title, class: "form-control" %>
		<span class="input-group-btn">
			<%= f.submit "Submit!", class: "btn btn-primary" %>
      </span>
	  </div>
	</div>
<% end %>

app/views/lists/edit.html.erb
<h1>Editing List</h1>

<%= render 'form' %>

<%= link_to 'Show', @list, class: "btn btn-default" %>
<%= link_to 'Back', lists_path, class: "btn btn-default" %>
<%= link_to 'Send to a Friend', send_form_path(@list.id), class: "btn btn-primary" %>

<hr/>

<h3>Add a new List Item</h3>
<%= form_for @list, url: {action: "add_item"}, method: "post" do |f| %>
	<div class="input-group">
	  <input type="text" id="new-item" name="item" class="form-control"/>
	<span class="input-group-btn">
		<button type="submit" class="btn btn-success">Add!</button>
	</span>
	</div>
<% end %>

<hr/>

<% if @list.list_items? %>
	<h3>Remove Items from this list</h3>
	<div class="list-group display-list">
	  <% @list.list_items.each do |item| %>
		  <div class="list-group-item">
			<div class="lead">
			  <%= item %>
			  <div class="pull-right">
				<%= link_to 'Remove', item, method: :delete, class: "btn btn-default text-danger" %>
			  </div>
			</div>
		  </div>
	  <% end %>
	</div>
<% end %>

app/views/lists/index.html.erb
<h2>Create new list!</h2>

<%= render 'form' %>

<hr/>

<% if @lists.any? %>
	<div class="list-group display-list">
	  <% @lists.each do |list| %>
		  <div class="list-group-item">
			<div class="lead"><%= list.title %>
				<div class="pull-right">
				  <%= link_to 'Show', list, class: "btn btn-sm btn-default" %>
				  <%= link_to 'Edit', edit_list_path(list), class: "btn btn-sm btn-default" %>
				  <%= link_to 'Destroy', list, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-sm btn-default" %>
				</div>
			</div>
		  </div>
	  <% end %>
	</div>
<% end %>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render 'form' %>

<%= link_to 'Back', lists_path, class: "btn btn-default" %>

app/views/lists/send_form.html.erb
<h1>Send this List to a friend!</h1>

<%= form_for @list, url: {action: "send_list"}, method: "post" do |f| %>
	<div class="form-group">
	  <label class="control-label" for="to_email">Your friend's email:</label>
	  <input class="form-control" type="text" name="to_email" id="to_email"/>
	</div>
	<div class="form-group">
	  <label class="control-label" for="message">Would you like to add a message?</label>
	  <textarea class="form-control" name="message" id="message" rows="10"></textarea>
	</div>
	<button type="submit" class="btn btn-primary">Send!</button>
	<%= link_to 'Cancel', @list, class: "btn btn-default" %>
<% end %>

app/views/lists/show.html.erb
<h1><%= @list.title %></h1>

<hr/>

<% if @list.list_items? %>
	<div class="list-group display-list">
	  <% @list.list_items.each do |item| %>
		  <div class="list-group-item">
			<div class="lead">
			  <%= item %>
			</div>
		  </div>
	  <% end %>
	</div>
<% end %>


<%= link_to 'Edit', edit_list_path(@list), class: "btn btn-default" %>
<%= link_to 'Back', lists_path, class: "btn btn-default" %>
<%= link_to 'Send to a Friend', send_form_path(@list.id), class: "btn btn-primary" %>

app/views/lists/unauthorized.html.erb
<p class="alert alert-warning">
  You aren't authorized to view this List!
</p>

<%= link_to "Back to Lists", lists_url, class: "btn btn-default" %>